version: '3'
services:

  # Backend
  steamcity-backend:
    build: ./steamcity-backend
    container_name: steamcity-backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - steamcity-frontend
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/attendees?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: lylio
      SPRING_DATASOURCE_PASSWORD: P@$$w0rd
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend
  steamcity-frontend:
    build: ./steamcity-frontend
    container_name: steamcity-frontend
    depends_on:
      - db
    ports:
      - 4200:80
    networks:
      - frontend

  # Database Service (MySQL)
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: attendees
      MYSQL_USER: lylio
      MYSQL_PASSWORD: P@$$w0rd
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
