version: '3'

services:
  # Database Service (Mysql)
  steamcity-mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: steamcity
      MYSQL_USER: steamcity
      MYSQL_PASSWORD: steamcity
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  # Backend Service (Spring Boot)
  steamcity-backend:
    build: ./steamcity-backend
    container_name: steamcity-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://steamcity-mysql:3306/steamcity?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: steamcity
      SPRING_DATASOURCE_PASSWORD: steamcity
    ports:
      - 8080
    links:
      - steamcity-mysql
    depends_on:
      - steamcity-mysql
    networks:
      - backend

  # Frontend Service (Angular)
  steamcity-frontend:
    build: ./steamcity-frontend
    container_name: steamcity-frontend
    ports:
      - 4200:80
    links:
      - steamcity-backend
    networks:
      - frontend

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
