# MySQL CREDENTIALS
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://:3306/steamcity_database?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: lylio
    password: P@$$w0rd
    initialization-mode: always


# LOGGING
logging:
  file: /home/lylio/Documents/logs/steamcity.log

# BANNER
spring.banner.location: classpath:banner.txt

# ENDPOINT MANAGEMENT
management:
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"